/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CoursePage } from '../../models/course-page';

export interface ListCourses$Params {
  page?: number;
  size?: number;
}

export function listCourses(http: HttpClient, rootUrl: string, params?: ListCourses$Params, context?: HttpContext): Observable<StrictHttpResponse<CoursePage>> {
  const rb = new RequestBuilder(rootUrl, listCourses.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CoursePage>;
    })
  );
}

listCourses.PATH = '/courses';
