/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Address {

  /**
   * Complement d'adresse (batiment, etage, etc.)
   */
  additionalInfo?: string;
  city: string;
  country?: string;
  postalCode: string;
  streetName: string;
  streetNumber?: string;
}
