/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditData {
  createdAt?: string;
  createdBy?: string;
  updatedAt?: string;
  updatedBy?: string;
  version?: number;
}
