/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CourseRequest {
  author: string;

  /**
   * Contenu libre du cours au format JSON
   */
  documentJson?: {
[key: string]: any;
};
  title: string;
}
