/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditData } from '../models/audit-data';
export interface Course {
  auditData?: AuditData;
  author: string;

  /**
   * Contenu libre du cours au format JSON
   */
  documentJson?: {
[key: string]: any;
};
  id: number;
  title: string;
}
