/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Course } from '../models/course';
export interface CoursePage {
  content: Array<Course>;
  first: boolean;
  last: boolean;
  pageNumber: number;
  pageSize: number;
  totalElements: number;
  totalPages: number;
}
