/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { AuditData } from '../models/audit-data';
export interface User {
  address?: Address;
  auditData?: AuditData;
  birthDate?: string;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  userName: string;
}
