/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
export interface UserRequest {
  address?: Address;
  birthDate?: string;
  email: string;
  firstName: string;
  lastName: string;
  userName: string;
}
