spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: myapp
    password: myapp
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: admin
      password: admin

swagger:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
